#!/usr/bin/env bash
# .claude/hooks/attribution-guard.sh — Block git commits with AI attribution footers
#
# Claude Code PreToolUse hook for the Bash tool.
# This hook intercepts git commit commands and blocks any that contain
# AI attribution footers (Co-Authored-By: ... @anthropic.com, Generated
# with Claude Code, etc.), forcing the AI to re-issue the commit without
# attribution. Matches on @anthropic.com email domain, not on name
# "Claude", to preserve legitimate human Co-Authored-By lines.
#
# Exit codes:
#   0 - Allow the tool call to proceed
#   2 - Block the tool call (with error message on stderr)

set -euo pipefail

# Read the tool call JSON from stdin
INPUT="$(cat)"

# Extract the command from the JSON input using python3 for reliable parsing
# Falls back to simple grep if python3 is unavailable
COMMAND=""
if command -v python3 >/dev/null 2>&1; then
    COMMAND="$(printf '%s' "${INPUT}" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('tool_input',{}).get('command',''))" 2>/dev/null || true)"
elif command -v jq >/dev/null 2>&1; then
    COMMAND="$(printf '%s' "${INPUT}" | jq -r '.tool_input.command // empty' 2>/dev/null || true)"
fi

# If we couldn't parse JSON, check the raw input as a fallback
if [[ -z "${COMMAND}" ]]; then
    COMMAND="${INPUT}"
fi

# Only check commands that start with git commit
# Must NOT match: "gh pr create" (PR body may mention Co-Authored-By)
# Must NOT match: "git log" or "git show" (may display attribution)
# Must match: "git commit -m ..." or "git commit --amend"
if ! printf '%s' "${COMMAND}" | grep -qE '(^|;|&&|\|)[[:space:]]*git[[:space:]]+commit\b'; then
    exit 0
fi

# Check for AI attribution patterns in the commit command
# Match on @anthropic.com email domain, not on name "Claude", to avoid
# false positives for human contributors named Claude (consistent with commit-msg hook)
ATTRIBUTION_FOUND=false

# Check for Co-Authored-By with @anthropic.com email domain
if printf '%s' "${COMMAND}" | grep -qiE 'Co-Authored-By:.*@anthropic\.com'; then
    ATTRIBUTION_FOUND=true
fi

if printf '%s' "${COMMAND}" | grep -qiE 'Co-Authored-By:.*noreply@anthropic'; then
    ATTRIBUTION_FOUND=true
fi

# Check for Claude Code generated footers
if printf '%s' "${COMMAND}" | grep -qiE 'Generated with.*Claude'; then
    ATTRIBUTION_FOUND=true
fi

if printf '%s' "${COMMAND}" | grep -qiE 'Generated by.*Claude'; then
    ATTRIBUTION_FOUND=true
fi

if printf '%s' "${COMMAND}" | grep -qiE 'Created by.*Claude'; then
    ATTRIBUTION_FOUND=true
fi

if [[ "${ATTRIBUTION_FOUND}" == "true" ]]; then
    echo "BLOCKED: Commit contains AI attribution footer (Co-Authored-By: Claude / Generated with Claude Code)." >&2
    echo "Per CLAUDE.md and .claude/rules/workflow-commit-standards.md:" >&2
    echo "  - DO NOT add attribution footers — No Co-Authored-By: Claude" >&2
    echo "  - Branches with Anthropic attribution footers are BLOCKED from merge" >&2
    echo "Re-issue the commit without the attribution footer." >&2
    exit 2
fi

exit 0
